name: Go CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
#          cache: false
          go-version-file: ./go.mod

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          go generate ./...
          go build

      - name: Test
        run: go test -v

      - name: Lint
        run: go vet
